Update  alpine check version workflow (#5)
* test

* git push

* test error

* update error

* Update .env

diff --git a/.github/workflows/alpine-check-version.yml b/.github/workflows/alpine-check-version.yml
--- a/.github/workflows/alpine-check-version.yml
+++ b/.github/workflows/alpine-check-version.yml
@@ -6,7 +6,7 @@ on:
   workflow_dispatch:
 
 jobs:
-  check-alpine-versions:
+  check-alpine-version:
     runs-on: ubuntu-latest
     outputs:
       update_alpine: ${{ steps.compare.outputs.update_alpine }}
@@ -29,7 +29,10 @@ jobs:
           | jq -r '.results[] | select(.digest == "'$ALPINE_DIGEST'") | select(.name | test("^[0-9]+\\.[0-9]+$")) | .name' \
           | head -n 1)"
 
-          : "${ALPINE_LATEST_VERSION:?Error: Unable to fetch current Alpine version}"
+          if [ -z "$ALPINE_LATEST_VERSION" ]; then
+            echo "::error::Unable to fetch current Alpine version"
+            exit 1
+          fi
 
           echo "version=${ALPINE_LATEST_VERSION}" >> "$GITHUB_OUTPUT"
 
@@ -45,15 +48,15 @@ jobs:
           fi
 
   create-pull-request:
-    needs: check-alpine-versions
+    needs: check-alpine-version
     runs-on: ubuntu-latest
-    if: ${{ needs.check-alpine-versions.outputs.update_alpine }}
+    if: ${{ needs.check-alpine-version.outputs.update_alpine }}
     steps:
       - uses: actions/checkout@v4
 
       - name: Update .env
         run: |
-          sed -i 's/^ALPINE_VERSION=.*/ALPINE_VERSION=${{ needs.check-alpine-versions.outputs.update_alpine }}/' .env
+          sed -i 's/^ALPINE_VERSION=.*/ALPINE_VERSION=${{ needs.check-alpine-version.outputs.update_alpine }}/' .env
           cat .env
 
       - name: Commit changes
@@ -61,22 +64,21 @@ jobs:
           git config user.name "github-actions"
           git config user.email "github-actions@users.noreply.github.com"
           git add .
-          git commit -m "📦 chore(deps): bump Alpine Linux to ${{ needs.check-alpine-versions.outputs.update_alpine }}"
+          git commit -m "📦 chore(deps): bump Alpine Linux to ${{ needs.check-alpine-version.outputs.update_alpine }}"
 
       - name: Push changes
-        if: ${{ steps.compare.outputs.update_alpine == 'true' }}
         uses: ad-m/github-push-action@master
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
-          branch: chore/update-alpine-linux-${{ needs.check-alpine-versions.outputs.update_alpine }}
+          branch: chore/update-alpine-linux-${{ needs.check-alpine-version.outputs.update_alpine }}
 
       - name: Create Pull Request
         uses: peter-evans/create-pull-request@v7
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
-          branch: chore/update-alpine-linux-${{ needs.check-alpine-versions.outputs.update_alpine }}
-          title: "[GithubActions] New Alpine Linux version `${{ needs.check-alpine-versions.outputs.update_alpine }}`"
+          branch: chore/update-alpine-linux-${{ needs.check-alpine-version.outputs.update_alpine }}
+          title: "[GithubActions] New Alpine Linux version `${{ needs.check-alpine-version.outputs.update_alpine }}`"
           body: |
             Automatically generated by a GitHub Action.
 
-              - Updates the Alpine Linux base image to version `${{ needs.check-alpine-versions.outputs.update_alpine }}`.
+              - Updates the Alpine Linux base image to version `${{ needs.check-alpine-version.outputs.update_alpine }}`.
